export const CATEGORIES = [
    "All",
    "Burgers",
    "Pizza",
    "Starters",
    "Sides",
    "Sandwiches",
    "Drinks",
    "Desserts"
];

export const MENU_ITEMS = [
    // ===== BURGERS =====
    {
        id: "menu_1",
        name: "Classic Gourmet Cheeseburger",
        price: 199,
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
        description: "Succulent grilled chicken patty layered with aged cheddar, crisp lettuce, ripe tomato and secret house mayo.",
        isVeg: false,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 680,
        prepTime: 12
    },
    {
        id: "menu_2",
        name: "Smoky BBQ Bacon & Chicken Burger",
        price: 249,
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
        description: "Tender chicken breast smothered in hickory BBQ sauce with melted cheese and caramelized red onions.",
        isVeg: false,
        isAvailable: true,
        isTrending: true,
        isPopular: false,
        calories: 750,
        prepTime: 15
    },
    {
        id: "menu_3",
        name: "Royal Paneer Crunch Burger",
        price: 179,
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1571407970349-bc4e5c90b133?auto=format&fit=crop&w=800&q=80",
        description: "Golden spiced panko paneer steak with crisp shredded romaine lettuce and zesty chili-mayo dressing.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 590,
        prepTime: 10
    },
    {
        id: "menu_4",
        name: "Fiery Mutton Double Delight Burger",
        price: 299,
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80",
        description: "Char-grilled mutton patty with pickled jalapenos, double melted cheese slice, and fiery house chili glaze.",
        isVeg: false,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 840,
        prepTime: 18
    },
    {
        id: "menu_5",
        name: "Crispy Coastal Fish Fillet Burger",
        price: 229,
        category: "Burgers",
        image: "https://images.unsplash.com/photo-1572440514411-007ad94543e5?auto=format&fit=crop&w=800&q=80",
        description: "Crisp golden batter-fried fish fillet topped with fresh herbs, tartar mayonnaise, and creamy cheddar.",
        isVeg: false,
        isAvailable: true,
        isTrending: false,
        isPopular: false,
        calories: 610,
        prepTime: 14
    },

    // ===== PIZZAS =====
    {
        id: "menu_6",
        name: "Artisan Margherita Pizza",
        price: 299,
        category: "Pizza",
        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80",
        description: "Classic stone-baked crust layered with rich San Marzano tomato sauce, fresh buffalo mozzarella, and aromatic basil.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 720,
        prepTime: 16
    },
    {
        id: "menu_7",
        name: "Smoky Tandoori Chicken Tikka Pizza",
        price: 389,
        category: "Pizza",
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
        description: "Charcoal-infused spiced chicken chunks, bell peppers, crunchy red onions, and abundant stringy mozzarella.",
        isVeg: false,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 880,
        prepTime: 20
    },
    {
        id: "menu_8",
        name: "Garden Fresh Veggie Supreme Pizza",
        price: 339,
        category: "Pizza",
        image: "https://images.unsplash.com/photo-1564982752979-3f937ebc4b19?auto=format&fit=crop&w=800&q=80",
        description: "Loaded with bell peppers, sliced button mushrooms, black olives, jalapenos, and melted golden mozzarella.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: false,
        calories: 680,
        prepTime: 18
    },
    {
        id: "menu_9",
        name: "Quattro Formaggi (Four Cheese) Pizza",
        price: 419,
        category: "Pizza",
        image: "https://images.unsplash.com/photo-1573821663912-b5164b4c6bb8?auto=format&fit=crop&w=800&q=80",
        description: "A luxurious blend of mozzarella, aged cheddar, parmesan shavings, and velvety cream sauce.",
        isVeg: true,
        isAvailable: true,
        isTrending: true,
        isPopular: false,
        calories: 920,
        prepTime: 18
    },

    // ===== STARTERS & SIDES =====
    {
        id: "menu_10",
        name: "Golden Herb Crispy French Fries",
        price: 129,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=800&q=80",
        description: "Crispy hand-cut russet potato fries tossed in rosemary sea salt and served with tangy dipping sauce.",
        isVeg: true,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 380,
        prepTime: 8
    },
    {
        id: "menu_11",
        name: "Loaded Melted Cheese Fries",
        price: 189,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1518080527399-a578d36cde12?auto=format&fit=crop&w=800&q=80",
        description: "Hot golden fries drenched in molten cheddar cheese sauce and garnished with spicy jalapenos.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 520,
        prepTime: 10
    },
    {
        id: "menu_12",
        name: "Artisan Cheesy Garlic Bread",
        price: 159,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1599599810694-d6212dc1add8?auto=format&fit=crop&w=800&q=80",
        description: "Warm toasted crusty bread infused with roasted garlic butter and bubbly melted mozzarella.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 410,
        prepTime: 10
    },
    {
        id: "menu_13",
        name: "Classic Parmesan Caesar Salad",
        price: 199,
        category: "Starters",
        image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80",
        description: "Crisp romaine ribbons, shaved parmesan reggiano, golden croutons, and authentic creamy Caesar dressing.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: false,
        calories: 280,
        prepTime: 8
    },
    {
        id: "menu_14",
        name: "Crispy Panko Onion Rings",
        price: 139,
        category: "Sides",
        image: "https://images.unsplash.com/photo-1639024471869-c0adf9893922?auto=format&fit=crop&w=800&q=80",
        description: "Thick sweet onion rings dipped in seasoned batter and panko breadcrumbs, fried to golden perfection.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: false,
        calories: 340,
        prepTime: 8
    },

    // ===== SANDWICHES =====
    {
        id: "menu_15",
        name: "Gourmet Grilled Chicken Club Sandwich",
        price: 199,
        category: "Sandwiches",
        image: "https://images.unsplash.com/photo-1553909990-fb05bff718b7?auto=format&fit=crop&w=800&q=80",
        description: "Three tiers of toasted artisan bread stuffed with herb-marinated grilled chicken, cheddar, tomatoes, and crisp lettuce.",
        isVeg: false,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 560,
        prepTime: 12
    },
    {
        id: "menu_16",
        name: "Paneer Tikka Panini Sandwich",
        price: 169,
        category: "Sandwiches",
        image: "https://images.unsplash.com/photo-1585238341710-4913dfdc3161?auto=format&fit=crop&w=800&q=80",
        description: "Spiced tandoori cottage cheese cubes, grilled peppers, and mint mayonnaise pressed in warm panini bread.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 490,
        prepTime: 10
    },

    // ===== DRINKS =====
    {
        id: "menu_17",
        name: "Velvet Silk Cappuccino",
        price: 149,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80",
        description: "Freshly pulled double espresso shot with steamed micro-foam milk and a gentle dusting of cocoa powder.",
        isVeg: true,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 140,
        prepTime: 5
    },
    {
        id: "menu_18",
        name: "Iced Caramel Macchiato",
        price: 189,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=800&q=80",
        description: "Chilled Arabica espresso layered over cold milk and finished with rich buttery caramel drizzle.",
        isVeg: true,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 220,
        prepTime: 5
    },
    {
        id: "menu_19",
        name: "Royal Spiced Masala Chai",
        price: 79,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
        description: "Slow-simmered Assam black tea with crushed cardamom, fresh ginger, cinnamon and whole milk.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 110,
        prepTime: 6
    },
    {
        id: "menu_20",
        name: "Fresh Mint Lime Mojito",
        price: 139,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80",
        description: "Muddled fresh mint leaves, tart key lime juice, sparkling soda water and chilled ice crystals.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 95,
        prepTime: 4
    },
    {
        id: "menu_21",
        name: "Belgian Hot Chocolate",
        price: 159,
        category: "Drinks",
        image: "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=800&q=80",
        description: "Rich dark Belgian cocoa melted with whole milk and topped with fluffy whipped cream.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: false,
        calories: 290,
        prepTime: 6
    },

    // ===== DESSERTS =====
    {
        id: "menu_22",
        name: "Molten Belgian Chocolate Lava Cake",
        price: 189,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=800&q=80",
        description: "Decadent dark chocolate soufflé cake with a warm flowing fudge center, served with vanilla ice cream.",
        isVeg: true,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 460,
        prepTime: 10
    },
    {
        id: "menu_23",
        name: "Madagascar Vanilla Bean Sundae",
        price: 149,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80",
        description: "Three scoops of aromatic vanilla bean ice cream drenched in warm dark chocolate fudge.",
        isVeg: true,
        isAvailable: true,
        isTrending: false,
        isPopular: true,
        calories: 380,
        prepTime: 5
    },
    {
        id: "menu_24",
        name: "New York Strawberry Cheesecake",
        price: 219,
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
        description: "Velvety smooth baked cream cheese on a buttery graham crust, glazed with fresh strawberry coulis.",
        isVeg: true,
        isAvailable: true,
        isTrending: true,
        isPopular: true,
        calories: 410,
        prepTime: 5
    }
];

export const SAMPLE_INVENTORY = [
    { _id: "inv_1", name: "Burger Bun", quantity: 120, unit: "pcs", threshold: 25 },
    { _id: "inv_2", name: "Pizza Base (10 inch)", quantity: 60, unit: "pcs", threshold: 15 },
    { _id: "inv_3", name: "Artisan Bread", quantity: 50, unit: "pcs", threshold: 12 },
    { _id: "inv_4", name: "Garlic Naan", quantity: 40, unit: "pcs", threshold: 8 },
    { _id: "inv_5", name: "Chicken Breast", quantity: 85, unit: "pcs", threshold: 15 },
    { _id: "inv_6", name: "Chicken Patty", quantity: 60, unit: "pcs", threshold: 12 },
    { _id: "inv_7", name: "Mutton Patty", quantity: 45, unit: "pcs", threshold: 10 },
    { _id: "inv_8", name: "Fish Fillet", quantity: 50, unit: "pcs", threshold: 10 },
    { _id: "inv_9", name: "Paneer", quantity: 35, unit: "kg", threshold: 5 },
    { _id: "inv_10", name: "Cheddar Cheese Slice", quantity: 180, unit: "pcs", threshold: 30 },
    { _id: "inv_11", name: "Mozzarella Cheese Block", quantity: 25, unit: "kg", threshold: 5 },
    { _id: "inv_12", name: "Parmesan Cheese", quantity: 8, unit: "kg", threshold: 2 },
    { _id: "inv_13", name: "Butter", quantity: 15, unit: "kg", threshold: 3 },
    { _id: "inv_14", name: "Fresh Milk", quantity: 60, unit: "liters", threshold: 12 },
    { _id: "inv_15", name: "Fresh Cream", quantity: 10, unit: "liters", threshold: 2 },
    { _id: "inv_16", name: "Fresh Tomato", quantity: 55, unit: "kg", threshold: 10 },
    { _id: "inv_17", name: "Red Onion", quantity: 60, unit: "kg", threshold: 12 },
    { _id: "inv_18", name: "Crisp Romaine Lettuce", quantity: 22, unit: "kg", threshold: 5 },
    { _id: "inv_19", name: "Cucumber", quantity: 18, unit: "kg", threshold: 4 },
    { _id: "inv_20", name: "Bell Pepper", quantity: 20, unit: "kg", threshold: 4 },
    { _id: "inv_21", name: "Fresh Mushroom", quantity: 12, unit: "kg", threshold: 3 },
    { _id: "inv_22", name: "Jalapenos", quantity: 10, unit: "kg", threshold: 2 },
    { _id: "inv_23", name: "Russet Potato", quantity: 120, unit: "kg", threshold: 25 },
    { _id: "inv_24", name: "Garlic Paste", quantity: 5, unit: "kg", threshold: 1 },
    { _id: "inv_25", name: "Fresh Mint & Lime", quantity: 8, unit: "kg", threshold: 2 },
    { _id: "inv_26", name: "Pizza Sauce", quantity: 15, unit: "liters", threshold: 3 },
    { _id: "inv_27", name: "Mayonnaise", quantity: 10, unit: "liters", threshold: 2 },
    { _id: "inv_28", name: "BBQ Sauce", quantity: 8, unit: "liters", threshold: 2 },
    { _id: "inv_29", name: "Chili Sauce", quantity: 8, unit: "liters", threshold: 2 },
    { _id: "inv_30", name: "Arabica Coffee Beans", quantity: 12, unit: "kg", threshold: 2 },
    { _id: "inv_31", name: "Assam Tea Leaves", quantity: 6, unit: "kg", threshold: 1 },
    { _id: "inv_32", name: "Refined Sugar", quantity: 30, unit: "kg", threshold: 5 },
    { _id: "inv_33", name: "Cocoa Powder", quantity: 5, unit: "kg", threshold: 1 },
    { _id: "inv_34", name: "Caramel Syrup", quantity: 6, unit: "liters", threshold: 1 },
    { _id: "inv_35", name: "Chocolate Syrup", quantity: 10, unit: "liters", threshold: 2 },
    { _id: "inv_36", name: "Vanilla Bean Ice Cream", quantity: 25, unit: "tubs", threshold: 5 },
    { _id: "inv_37", name: "Fresh Strawberries", quantity: 10, unit: "kg", threshold: 2 },
    { _id: "inv_38", name: "Soda Water", quantity: 80, unit: "bottles", threshold: 20 }
];
